### PR TITLE
fix: Conditionally pass SCM provider env variables

### PR DESCRIPTION
**Pull request by mjasion**

### CODE REVIEW

**Review by jesper7 — CHANGES_REQUESTED** [review]
About the URLs - these are default in the Studio images. 
Can we please not store the env variables in the ConfigMap if the URLs are unset? This avoids duplication

**Comment by mjasion** [comment]
> About the URLs - these are default in the Studio images. Can we please not store the env variables in the ConfigMap if the URLs are unset? This avoids duplication

How about hiding the scm parameters groups if the scm is not enabled?

**Comment by jesper7** [comment]
> How about hiding the scm parameters groups if the scm is not enabled?

To be on the safe side, we should do both. 
In case the SCM is enabled, we still don't want to keep defaults such as `github.com` for `GITHUB_URL` considering that it's already default in the Docker images

**Comment by omesser** [comment]
👎 duplication of default values
we should just condition setting the env vars by being passed a non empty string value imo

**Review by jesper7 — APPROVED** [review]

**Pull request merged**
