### PR TITLE
Set a sensible value for `localStorage.size`

### PR DESCRIPTION
**Pull request by 0x2b3bfa0**
It's problematic on self-hosted deployments, especially with the `1Gi` default size; let's keep it for people who need it and know what they're doing?

Alternatively, perhaps increase size to `20Gi` as well?

### CODE REVIEW

**Comment by shcheklein** [comment]
what is it used for in our cluster? if we don't have a local storage, what kind of storage is it using instead?

**Comment by mjasion** [comment]
@shcheklein The node storage. Node allows to allocate storage until it will node storage will not be lower that 10% of the total disk space or 10GB(whichever is smaller)

**Comment by mjasion** [comment]
@0x2b3bfa0 I would disable it for studio-worker as well

**Comment by shcheklein** [comment]
so, what was the localStorage used for ? why is it needed at all? (can we clarify this in helm comments / docs)?

**Comment by 0x2b3bfa0** [comment]
`localStorage` is needed for dependency (virtual environment) caching; I'll just bump the default value to `50Gi` mirroring our production deployment; it's the easiest.

**Comment by 0x2b3bfa0** [comment]
@shcheklein / @mjasion, better now?

**Comment by shcheklein** [comment]
> @shcheklein / @mjasion, better now?

- there is still no explanation for what it is used for
- is it a permanent storage (survives pod restarts / redeployments)?
- if we disable it - where does it store those env then? what kind of other storages do we have on pods?

**Comment by 0x2b3bfa0** [comment]
> _there is still no explanation for what it is used for_

* https://github.com/iterative/helm-charts/pull/435#issuecomment-2209335042

> _is it a permanent storage (survives pod restarts / redeployments)?_

Not by default; it'll be ephemeral.

> _if we disable it - where does it store those env then? what kind of other storages do we have on pods?_

It would use the default `/tmp` (with no guarantees on free space availability)

**Comment by shcheklein** [comment]
> https://github.com/iterative/helm-charts/pull/435#issuecomment-2209335042

I mean the docs / or helm comments. We assume that help is used by customers, right? We should try to put some explanations if possible (not sure if we do this atm, but we were getting negative feedback about this recently).

But even for me, deploying this- It's hard to understand the purpose, if I need this or not, etc.

> It would use the default /tmp (with no guarantees on free space availability; not a good idea)

okay, so, space guarantee is the only thing here? (just to make sure)

**Comment by 0x2b3bfa0** [comment]
> _okay, so, space guarantee is the only thing here? (just to make sure)_

Yes, basically it guarantees `/tmp/local` has enough free space, is writable and so on (i.e. is usable)

**Comment by 0x2b3bfa0** [comment]
> _I mean the docs / or helm comments. We assume that help is used by customers, right? We should try to put some explanations if possible (not sure if we do this atm, but we were getting negative feedback about this recently)._

Right; let me try to fix it.

> _But even for me, deploying this- It's hard to understand the purpose, if I need this or not, etc._

Long story short, it's needed to initialize & store virtual environments.

**Comment by 0x2b3bfa0** [comment]
Happier?
https://github.com/iterative/helm-charts/blob/8b0df92c79fce8ba5191c8f511ea8b834faaa9cc/charts/studio/values.yaml#L706

**Comment by shcheklein** [comment]
> Happier?

Well :) nobody outside would understand this ... even internal users - some people will not be able to connect the dots. Anyways, that's fine considering that we don't have much of the docs for the rest of the Helm anyways. It should be a separate issue / epic if we can get to it at some point.

Not a blocker, @0x2b3bfa0 . Thanks for taking care of this.

**Review by shcheklein — APPROVED** [review]

**Pull request merged**
