### PR TITLE
chore(Webhook): Comment out by default URLS 

### PR DESCRIPTION
**Pull request by omesser**
In most cases, no need to pass this.
Adding comments to explain, commenting out by default

### CODE REVIEW

**Comment by jesper7** [comment]
> re: CI - do we really need a version bump for this?

Not for the `Lint and Test Charts`, but the workflow is WIP and currently broken, so feel free to ignore it.

**Comment by omesser** [comment]
> There are some downsides to commenting it out:
> 
> 1. As far as I know, it's not common practice in most Helm charts
> 2. The variable won't be visible if we use some tool to autogenerate the documentation for all variables

@jesper7 :
1. very common. This is THE way to say "hey, this is an optional setting". seen it a lot. it's correct to NOT pass optional env vars than set them to empty strings:
-  it spams the execution env
- you're counting on someone handling empty strings correctly in some other part of the code
- empty strings can have meaning (generalized to: sometimes defaults need to not be overridden, instead of overridden with the same value which is duplication and hides source of the value)

Here's some random example: https://github.com/grafana/helm-charts/blob/main/charts/enterprise-logs-simple/values.yaml#L154
Again, I'm positive this is a very wide-spread practice, and there is no alternative in YAML/chart value semantics which is exactly the same

2. what tool? theoretical or real concern? 😓

**Comment by omesser** [comment]
To be clear, I am not sure if not passing this is safe, I only know it's a common practice and it sounded like it's the right thing to do from the discussion today, so need your review /knowledge about what happens in studio if those we hook urls just are not set. It should be ok from the code... But :shrug:

**Comment by omesser** [comment]
@jesper7 @mjasion - ping. this is a small one 😄

**Comment by jesper7** [comment]
> very common. This is THE way to say "hey, this is an optional setting". seen it a lot. it's correct to NOT pass optional env vars than set them to empty strings:
> - it spams the execution env
> - you're counting on someone handling empty strings correctly in some other part of the code
> - empty strings can have meaning (generalized to: sometimes defaults need to not be overridden, instead of overridden with the same value which is duplication and hides source of the value)

We actually don't pass the variables to the containers if they are empty. Example:
https://github.com/iterative/helm-charts/blob/4cac4589847184c4154e9d37072b94a1eb04d358/charts/studio/templates/configmap-studio.yaml#L86-L88

> Here's some random example: https://github.com/grafana/helm-charts/blob/main/charts/enterprise-logs-simple/values.yaml#L154

That's fair enough. I think ultimately it comes down to whether or not you plan to autogenerate documentation based on the `values.yaml` file. In Grafana's case, they aren't doing that, but it's something we would like to do.

> what tool? theoretical or real concern?

There are plenty of real-world examples:

**ingress-nginx**
https://github.com/kubernetes/ingress-nginx/tree/main/charts/ingress-nginx
https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/README.md.gotmpl#L229
https://github.com/norwoodj/helm-docs

**bitnami**
https://github.com/bitnami/charts/tree/main/bitnami/clickhouse
https://github.com/bitnami/charts/blob/main/.github/workflows/generate-chart-readme.yml

**Comment by mjasion** [comment]
> > Here's some random example: https://github.com/grafana/helm-charts/blob/main/charts/enterprise-logs-simple/values.yaml#L154
> 
> That's fair enough. I think ultimately it comes down to whether or not you plan to autogenerate documentation based on the `values.yaml` file. In Grafana's case, they aren't doing that, but it's something we would like to do.

My 2 cents:
1. [helm-docs](https://github.com/norwoodj/helm-docs) allows to render a default value, even if the value is `""` - https://github.com/iterative/helm-charts/pull/107/files#diff-11bc43f675a4daee6e17f65993651502f7f00be21b772da29dc1bd1a622ad4faR80-R81
2. I understand @jesper7 point, and this is how I went with extracting the webhook hostname outside object: https://github.com/iterative/helm-charts/pull/107 . If I understood, this is the main reason, why we need to have this setting.

**Comment by mjasion** [comment]
I am closing this, and let's continue in #107  :-)

**Pull request closed without merging**
