### PR TITLE
Update DataChain worker liveness probe

### PR DESCRIPTION
**Pull request by dreadatour**
This updates liveness probe command for DVCx worker k8s deployment.

Should be merged after https://github.com/iterative/studio/pull/9174 will be merged and released.

### CODE REVIEW

**Review by mjasion — APPROVED** [review]

**Comment by dreadatour** [comment]
Waiting this PR to be merged and deployed to dev and prod: https://github.com/iterative/studio/pull/9247

**Comment by shcheklein** [comment]
@dreadatour what is the status of this?

**Comment by shcheklein** [comment]
folks @dreadatour and @iterative/platform - what is the status here?

**Comment by shcheklein** [comment]
folks @dreadatour and @iterative/platform - what is the status here?

**Comment by 0x2b3bfa0** [comment]
It looks like https://github.com/iterative/studio/pull/9174 mentioned on https://github.com/iterative/helm-charts/pull/325#issue-2136284740 was released 4+ months (!) ago; after https://github.com/iterative/helm-charts/pull/438 we no longer need this liveness probe.

**Still,** we should have _some_ liveness probe, maybe making sure that the Celery workers are storing heartbeats into Redis or something that ensures us the pod is healthy and ready to ingest new tasks.

**Comment by 0x2b3bfa0** [comment]
So there's nothing wrong with this pull request and we can merge it, but `/app/bin/liveness-probe.sh` will have to be redesigned first.

**Comment by shcheklein** [comment]
there was some code duplication around SA liveness probes and tests on the Studio side that we also should cleanup along the way

**Comment by 0x2b3bfa0** [comment]
Maybe https://github.com/iterative/studio/pull/10307#discussion1683252817 can provide better readiness/liveness probes for DataChain that anything else, if it gets merged.

**Comment by 0x2b3bfa0** [comment]
Stale; opened https://github.com/iterative/helm-charts/issues/504 to track this

**Pull request closed without merging**
