### PR TITLE
feat(helm-chart): Add support for passing multiple custom certificate authorities

### PR DESCRIPTION
**Pull request by mjasion**
This PR add support setting multiple Custom CA Certificates by new value `customCaCertificates` with `list type` and deprecates previous one `customCaCertificate` with `string type`.

### CODE REVIEW

**Review by jesper7 — COMMENTED** [review]
LGTM can you just update the PR description to summarize the changes (especially the breaking change)?

**Review by 0x2b3bfa0 — APPROVED** [review]
Looks awesome to me!

**Comment by 0x2b3bfa0** [comment]
> _especially the breaking change_

It looks like it's not a breaking change, but a soft deprecation.

**Comment by mjasion** [comment]
Description Updated @jesper7 @0x2b3bfa0

**Pull request merged**
