### PR TITLE
Remove duplicate managed-by labels

### PR DESCRIPTION
**Pull request by 0x2b3bfa0**
https://github.com/iterative/helm-charts/blob/9d37015e63dd4fdb1698517eb226cbb4562bee87/charts/studio/templates/_helpers.tpl#L43

### CODE REVIEW

**Comment by 0x2b3bfa0** [comment]
@iterative/platform, YOLO-merging this one because it’s a big bug; I have moved the other change, subject to human considerations, to a separate pull request.

**Comment by jesper7** [comment]
Thanks! Looks good :+1: 
Since it was a time-sensitive, critical bug, I have no objections to the force merge

**Comment by jesper7** [comment]
Thank you!

**Comment by 0x2b3bfa0** [comment]
For the record, this was the error message, when running `make skaffold-dev`

```
Error: INSTALLATION FAILED: error while running post render on files: error while running command /usr/local/bin/skaffold. error output:
reading Kubernetes YAML: yaml: unmarshal errors:
  line 12: mapping key "app.kubernetes.io/managed-by" already defined at line 11
exit status 1
````

**Comment by 0x2b3bfa0** [comment]
https://pkg.go.dev/github.com/GoogleContainerTools/skaffold/v2@v2.7.1/pkg/skaffold/yaml#UnmarshalStrict

UnmarshalStrict is like Unmarshal except that any fields that are found in the data that do not have corresponding struct members, or mapping keys that are duplicates, will result in an error

**Pull request merged**
